#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TraiCay.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_TraiCay")]
	public partial class QL_TraiCayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_ADMIN(_ADMIN instance);
    partial void Update_ADMIN(_ADMIN instance);
    partial void Delete_ADMIN(_ADMIN instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void Insert_USER(_USER instance);
    partial void Update_USER(_USER instance);
    partial void Delete_USER(_USER instance);
    partial void InsertCHITIETDONHANG(CHITIETDONHANG instance);
    partial void UpdateCHITIETDONHANG(CHITIETDONHANG instance);
    partial void DeleteCHITIETDONHANG(CHITIETDONHANG instance);
    partial void InsertCHITIETGIOHANG(CHITIETGIOHANG instance);
    partial void UpdateCHITIETGIOHANG(CHITIETGIOHANG instance);
    partial void DeleteCHITIETGIOHANG(CHITIETGIOHANG instance);
    partial void InsertCHITIETVANCHUYEN(CHITIETVANCHUYEN instance);
    partial void UpdateCHITIETVANCHUYEN(CHITIETVANCHUYEN instance);
    partial void DeleteCHITIETVANCHUYEN(CHITIETVANCHUYEN instance);
    partial void InsertDONHANG(DONHANG instance);
    partial void UpdateDONHANG(DONHANG instance);
    partial void DeleteDONHANG(DONHANG instance);
    partial void InsertDONVIVANCHUYEN(DONVIVANCHUYEN instance);
    partial void UpdateDONVIVANCHUYEN(DONVIVANCHUYEN instance);
    partial void DeleteDONVIVANCHUYEN(DONVIVANCHUYEN instance);
    partial void InsertGIAODICH(GIAODICH instance);
    partial void UpdateGIAODICH(GIAODICH instance);
    partial void DeleteGIAODICH(GIAODICH instance);
    partial void InsertGIOHANG(GIOHANG instance);
    partial void UpdateGIOHANG(GIOHANG instance);
    partial void DeleteGIOHANG(GIOHANG instance);
    partial void InsertLOAITRAICAY(LOAITRAICAY instance);
    partial void UpdateLOAITRAICAY(LOAITRAICAY instance);
    partial void DeleteLOAITRAICAY(LOAITRAICAY instance);
    partial void InsertNHACC_TRAICAY(NHACC_TRAICAY instance);
    partial void UpdateNHACC_TRAICAY(NHACC_TRAICAY instance);
    partial void DeleteNHACC_TRAICAY(NHACC_TRAICAY instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHASANXUAT(NHASANXUAT instance);
    partial void UpdateNHASANXUAT(NHASANXUAT instance);
    partial void DeleteNHASANXUAT(NHASANXUAT instance);
    partial void InsertNHASX_TRAICAY(NHASX_TRAICAY instance);
    partial void UpdateNHASX_TRAICAY(NHASX_TRAICAY instance);
    partial void DeleteNHASX_TRAICAY(NHASX_TRAICAY instance);
    partial void InsertTRAICAY(TRAICAY instance);
    partial void UpdateTRAICAY(TRAICAY instance);
    partial void DeleteTRAICAY(TRAICAY instance);
    #endregion
		
		public QL_TraiCayDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_TraiCayConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TraiCayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TraiCayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TraiCayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TraiCayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_ADMIN> _ADMINs
		{
			get
			{
				return this.GetTable<_ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<_USER> _USERs
		{
			get
			{
				return this.GetTable<_USER>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETGIOHANG> CHITIETGIOHANGs
		{
			get
			{
				return this.GetTable<CHITIETGIOHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETVANCHUYEN> CHITIETVANCHUYENs
		{
			get
			{
				return this.GetTable<CHITIETVANCHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<DONHANG> DONHANGs
		{
			get
			{
				return this.GetTable<DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<DONVIVANCHUYEN> DONVIVANCHUYENs
		{
			get
			{
				return this.GetTable<DONVIVANCHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<GIAODICH> GIAODICHes
		{
			get
			{
				return this.GetTable<GIAODICH>();
			}
		}
		
		public System.Data.Linq.Table<GIOHANG> GIOHANGs
		{
			get
			{
				return this.GetTable<GIOHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAITRAICAY> LOAITRAICAYs
		{
			get
			{
				return this.GetTable<LOAITRAICAY>();
			}
		}
		
		public System.Data.Linq.Table<NHACC_TRAICAY> NHACC_TRAICAYs
		{
			get
			{
				return this.GetTable<NHACC_TRAICAY>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHASANXUAT> NHASANXUATs
		{
			get
			{
				return this.GetTable<NHASANXUAT>();
			}
		}
		
		public System.Data.Linq.Table<NHASX_TRAICAY> NHASX_TRAICAYs
		{
			get
			{
				return this.GetTable<NHASX_TRAICAY>();
			}
		}
		
		public System.Data.Linq.Table<TRAICAY> TRAICAYs
		{
			get
			{
				return this.GetTable<TRAICAY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_ADMIN]")]
	public partial class _ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAAD;
		
		private string _MATK;
		
		private string _HOTEN;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAADChanging(string value);
    partial void OnMAADChanged();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    #endregion
		
		public _ADMIN()
		{
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAAD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAAD
		{
			get
			{
				return this._MAAD;
			}
			set
			{
				if ((this._MAAD != value))
				{
					this.OnMAADChanging(value);
					this.SendPropertyChanging();
					this._MAAD = value;
					this.SendPropertyChanged("MAAD");
					this.OnMAADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN__ADMIN", Storage="_TAIKHOAN", ThisKey="MATK", OtherKey="MATK", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue._ADMINs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value._ADMINs.Add(this);
						this._MATK = value.MATK;
					}
					else
					{
						this._MATK = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATK;
		
		private string _HOTEN;
		
		private string _MATKHAU;
		
		private string _USERNAME;
		
		private EntitySet<_ADMIN> @__ADMINs;
		
		private EntitySet<_USER> @__USERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this.@__ADMINs = new EntitySet<_ADMIN>(new Action<_ADMIN>(this.attach__ADMINs), new Action<_ADMIN>(this.detach__ADMINs));
			this.@__USERs = new EntitySet<_USER>(new Action<_USER>(this.attach__USERs), new Action<_USER>(this.detach__USERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN__ADMIN", Storage="__ADMINs", ThisKey="MATK", OtherKey="MATK")]
		public EntitySet<_ADMIN> _ADMINs
		{
			get
			{
				return this.@__ADMINs;
			}
			set
			{
				this.@__ADMINs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN__USER", Storage="__USERs", ThisKey="MATK", OtherKey="MATK")]
		public EntitySet<_USER> _USERs
		{
			get
			{
				return this.@__USERs;
			}
			set
			{
				this.@__USERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__ADMINs(_ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach__ADMINs(_ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach__USERs(_USER entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach__USERs(_USER entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_USER]")]
	public partial class _USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAUSER;
		
		private string _MATK;
		
		private string _MAGH;
		
		private string _HOTEN;
		
		private string _SDT;
		
		private string _AVARTA;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private EntitySet<GIAODICH> _GIAODICHes;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
		private EntityRef<GIOHANG> _GIOHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAUSERChanging(string value);
    partial void OnMAUSERChanged();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnMAGHChanging(string value);
    partial void OnMAGHChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnAVARTAChanging(string value);
    partial void OnAVARTAChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public _USER()
		{
			this._GIAODICHes = new EntitySet<GIAODICH>(new Action<GIAODICH>(this.attach_GIAODICHes), new Action<GIAODICH>(this.detach_GIAODICHes));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			this._GIOHANG = default(EntityRef<GIOHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUSER", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAUSER
		{
			get
			{
				return this._MAUSER;
			}
			set
			{
				if ((this._MAUSER != value))
				{
					this.OnMAUSERChanging(value);
					this.SendPropertyChanging();
					this._MAUSER = value;
					this.SendPropertyChanged("MAUSER");
					this.OnMAUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MAGH
		{
			get
			{
				return this._MAGH;
			}
			set
			{
				if ((this._MAGH != value))
				{
					if (this._GIOHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGHChanging(value);
					this.SendPropertyChanging();
					this._MAGH = value;
					this.SendPropertyChanged("MAGH");
					this.OnMAGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVARTA", DbType="NVarChar(50)")]
		public string AVARTA
		{
			get
			{
				return this._AVARTA;
			}
			set
			{
				if ((this._AVARTA != value))
				{
					this.OnAVARTAChanging(value);
					this.SendPropertyChanging();
					this._AVARTA = value;
					this.SendPropertyChanged("AVARTA");
					this.OnAVARTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_USER_GIAODICH", Storage="_GIAODICHes", ThisKey="MAUSER", OtherKey="MAUSER")]
		public EntitySet<GIAODICH> GIAODICHes
		{
			get
			{
				return this._GIAODICHes;
			}
			set
			{
				this._GIAODICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN__USER", Storage="_TAIKHOAN", ThisKey="MATK", OtherKey="MATK", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue._USERs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value._USERs.Add(this);
						this._MATK = value.MATK;
					}
					else
					{
						this._MATK = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOHANG__USER", Storage="_GIOHANG", ThisKey="MAGH", OtherKey="MAGH", IsForeignKey=true)]
		public GIOHANG GIOHANG
		{
			get
			{
				return this._GIOHANG.Entity;
			}
			set
			{
				GIOHANG previousValue = this._GIOHANG.Entity;
				if (((previousValue != value) 
							|| (this._GIOHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIOHANG.Entity = null;
						previousValue._USERs.Remove(this);
					}
					this._GIOHANG.Entity = value;
					if ((value != null))
					{
						value._USERs.Add(this);
						this._MAGH = value.MAGH;
					}
					else
					{
						this._MAGH = default(string);
					}
					this.SendPropertyChanged("GIOHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAODICHes(GIAODICH entity)
		{
			this.SendPropertyChanging();
			entity._USER = this;
		}
		
		private void detach_GIAODICHes(GIAODICH entity)
		{
			this.SendPropertyChanging();
			entity._USER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANG")]
	public partial class CHITIETDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADH;
		
		private string _MATC;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _GHICHU;
		
		private EntityRef<DONHANG> _DONHANG;
		
		private EntityRef<TRAICAY> _TRAICAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADHChanging(string value);
    partial void OnMADHChanged();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public CHITIETDONHANG()
		{
			this._DONHANG = default(EntityRef<DONHANG>);
			this._TRAICAY = default(EntityRef<TRAICAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					if (this._DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					if (this._TRAICAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(100)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_DONHANG", ThisKey="MADH", OtherKey="MADH", IsForeignKey=true)]
		public DONHANG DONHANG
		{
			get
			{
				return this._DONHANG.Entity;
			}
			set
			{
				DONHANG previousValue = this._DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANG.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._DONHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MADH = value.MADH;
					}
					else
					{
						this._MADH = default(string);
					}
					this.SendPropertyChanged("DONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_CHITIETDONHANG", Storage="_TRAICAY", ThisKey="MATC", OtherKey="MATC", IsForeignKey=true)]
		public TRAICAY TRAICAY
		{
			get
			{
				return this._TRAICAY.Entity;
			}
			set
			{
				TRAICAY previousValue = this._TRAICAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAICAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAICAY.Entity = null;
						previousValue.CHITIETDONHANGs.Remove(this);
					}
					this._TRAICAY.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGs.Add(this);
						this._MATC = value.MATC;
					}
					else
					{
						this._MATC = default(string);
					}
					this.SendPropertyChanged("TRAICAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETGIOHANG")]
	public partial class CHITIETGIOHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATC;
		
		private string _MAGH;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<GIOHANG> _GIOHANG;
		
		private EntityRef<TRAICAY> _TRAICAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnMAGHChanging(string value);
    partial void OnMAGHChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CHITIETGIOHANG()
		{
			this._GIOHANG = default(EntityRef<GIOHANG>);
			this._TRAICAY = default(EntityRef<TRAICAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					if (this._TRAICAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAGH
		{
			get
			{
				return this._MAGH;
			}
			set
			{
				if ((this._MAGH != value))
				{
					if (this._GIOHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAGHChanging(value);
					this.SendPropertyChanging();
					this._MAGH = value;
					this.SendPropertyChanged("MAGH");
					this.OnMAGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOHANG_CHITIETGIOHANG", Storage="_GIOHANG", ThisKey="MAGH", OtherKey="MAGH", IsForeignKey=true)]
		public GIOHANG GIOHANG
		{
			get
			{
				return this._GIOHANG.Entity;
			}
			set
			{
				GIOHANG previousValue = this._GIOHANG.Entity;
				if (((previousValue != value) 
							|| (this._GIOHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIOHANG.Entity = null;
						previousValue.CHITIETGIOHANGs.Remove(this);
					}
					this._GIOHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETGIOHANGs.Add(this);
						this._MAGH = value.MAGH;
					}
					else
					{
						this._MAGH = default(string);
					}
					this.SendPropertyChanged("GIOHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_CHITIETGIOHANG", Storage="_TRAICAY", ThisKey="MATC", OtherKey="MATC", IsForeignKey=true)]
		public TRAICAY TRAICAY
		{
			get
			{
				return this._TRAICAY.Entity;
			}
			set
			{
				TRAICAY previousValue = this._TRAICAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAICAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAICAY.Entity = null;
						previousValue.CHITIETGIOHANGs.Remove(this);
					}
					this._TRAICAY.Entity = value;
					if ((value != null))
					{
						value.CHITIETGIOHANGs.Add(this);
						this._MATC = value.MATC;
					}
					else
					{
						this._MATC = default(string);
					}
					this.SendPropertyChanged("TRAICAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETVANCHUYEN")]
	public partial class CHITIETVANCHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADV;
		
		private string _MADH;
		
		private System.Nullable<decimal> _THANHTIEN;
		
		private string _TINHTRANG;
		
		private EntityRef<DONHANG> _DONHANG;
		
		private EntityRef<DONVIVANCHUYEN> _DONVIVANCHUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnMADHChanging(string value);
    partial void OnMADHChanged();
    partial void OnTHANHTIENChanging(System.Nullable<decimal> value);
    partial void OnTHANHTIENChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public CHITIETVANCHUYEN()
		{
			this._DONHANG = default(EntityRef<DONHANG>);
			this._DONVIVANCHUYEN = default(EntityRef<DONVIVANCHUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					if (this._DONVIVANCHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					if (this._DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Money")]
		public System.Nullable<decimal> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(50)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETVANCHUYEN", Storage="_DONHANG", ThisKey="MADH", OtherKey="MADH", IsForeignKey=true)]
		public DONHANG DONHANG
		{
			get
			{
				return this._DONHANG.Entity;
			}
			set
			{
				DONHANG previousValue = this._DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANG.Entity = null;
						previousValue.CHITIETVANCHUYENs.Remove(this);
					}
					this._DONHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETVANCHUYENs.Add(this);
						this._MADH = value.MADH;
					}
					else
					{
						this._MADH = default(string);
					}
					this.SendPropertyChanged("DONHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVIVANCHUYEN_CHITIETVANCHUYEN", Storage="_DONVIVANCHUYEN", ThisKey="MADV", OtherKey="MADV", IsForeignKey=true)]
		public DONVIVANCHUYEN DONVIVANCHUYEN
		{
			get
			{
				return this._DONVIVANCHUYEN.Entity;
			}
			set
			{
				DONVIVANCHUYEN previousValue = this._DONVIVANCHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._DONVIVANCHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONVIVANCHUYEN.Entity = null;
						previousValue.CHITIETVANCHUYENs.Remove(this);
					}
					this._DONVIVANCHUYEN.Entity = value;
					if ((value != null))
					{
						value.CHITIETVANCHUYENs.Add(this);
						this._MADV = value.MADV;
					}
					else
					{
						this._MADV = default(string);
					}
					this.SendPropertyChanged("DONVIVANCHUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANG")]
	public partial class DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADH;
		
		private System.Nullable<decimal> _THANHTIEN;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntitySet<CHITIETVANCHUYEN> _CHITIETVANCHUYENs;
		
		private EntitySet<GIAODICH> _GIAODICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADHChanging(string value);
    partial void OnMADHChanged();
    partial void OnTHANHTIENChanging(System.Nullable<decimal> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public DONHANG()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._CHITIETVANCHUYENs = new EntitySet<CHITIETVANCHUYEN>(new Action<CHITIETVANCHUYEN>(this.attach_CHITIETVANCHUYENs), new Action<CHITIETVANCHUYEN>(this.detach_CHITIETVANCHUYENs));
			this._GIAODICHes = new EntitySet<GIAODICH>(new Action<GIAODICH>(this.attach_GIAODICHes), new Action<GIAODICH>(this.detach_GIAODICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Money")]
		public System.Nullable<decimal> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MADH", OtherKey="MADH")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_CHITIETVANCHUYEN", Storage="_CHITIETVANCHUYENs", ThisKey="MADH", OtherKey="MADH")]
		public EntitySet<CHITIETVANCHUYEN> CHITIETVANCHUYENs
		{
			get
			{
				return this._CHITIETVANCHUYENs;
			}
			set
			{
				this._CHITIETVANCHUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_GIAODICH", Storage="_GIAODICHes", ThisKey="MADH", OtherKey="MADH")]
		public EntitySet<GIAODICH> GIAODICHes
		{
			get
			{
				return this._GIAODICHes;
			}
			set
			{
				this._GIAODICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = null;
		}
		
		private void attach_CHITIETVANCHUYENs(CHITIETVANCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = this;
		}
		
		private void detach_CHITIETVANCHUYENs(CHITIETVANCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = null;
		}
		
		private void attach_GIAODICHes(GIAODICH entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = this;
		}
		
		private void detach_GIAODICHes(GIAODICH entity)
		{
			this.SendPropertyChanging();
			entity.DONHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVIVANCHUYEN")]
	public partial class DONVIVANCHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADV;
		
		private string _TENDONVI;
		
		private EntitySet<CHITIETVANCHUYEN> _CHITIETVANCHUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADVChanging(string value);
    partial void OnMADVChanged();
    partial void OnTENDONVIChanging(string value);
    partial void OnTENDONVIChanged();
    #endregion
		
		public DONVIVANCHUYEN()
		{
			this._CHITIETVANCHUYENs = new EntitySet<CHITIETVANCHUYEN>(new Action<CHITIETVANCHUYEN>(this.attach_CHITIETVANCHUYENs), new Action<CHITIETVANCHUYEN>(this.detach_CHITIETVANCHUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDONVI", DbType="NVarChar(50)")]
		public string TENDONVI
		{
			get
			{
				return this._TENDONVI;
			}
			set
			{
				if ((this._TENDONVI != value))
				{
					this.OnTENDONVIChanging(value);
					this.SendPropertyChanging();
					this._TENDONVI = value;
					this.SendPropertyChanged("TENDONVI");
					this.OnTENDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVIVANCHUYEN_CHITIETVANCHUYEN", Storage="_CHITIETVANCHUYENs", ThisKey="MADV", OtherKey="MADV")]
		public EntitySet<CHITIETVANCHUYEN> CHITIETVANCHUYENs
		{
			get
			{
				return this._CHITIETVANCHUYENs;
			}
			set
			{
				this._CHITIETVANCHUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETVANCHUYENs(CHITIETVANCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DONVIVANCHUYEN = this;
		}
		
		private void detach_CHITIETVANCHUYENs(CHITIETVANCHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DONVIVANCHUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAODICH")]
	public partial class GIAODICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAUSER;
		
		private string _MADH;
		
		private string _HINHTHUC;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _GHICHU;
		
		private System.Nullable<System.DateTime> _NGAYMUA;
		
		private string _TRANGTHAI;
		
		private EntityRef<_USER> @__USER;
		
		private EntityRef<DONHANG> _DONHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAUSERChanging(string value);
    partial void OnMAUSERChanged();
    partial void OnMADHChanging(string value);
    partial void OnMADHChanged();
    partial void OnHINHTHUCChanging(string value);
    partial void OnHINHTHUCChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnNGAYMUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYMUAChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public GIAODICH()
		{
			this.@__USER = default(EntityRef<_USER>);
			this._DONHANG = default(EntityRef<DONHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAUSER", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAUSER
		{
			get
			{
				return this._MAUSER;
			}
			set
			{
				if ((this._MAUSER != value))
				{
					if (this.@__USER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAUSERChanging(value);
					this.SendPropertyChanging();
					this._MAUSER = value;
					this.SendPropertyChanged("MAUSER");
					this.OnMAUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADH
		{
			get
			{
				return this._MADH;
			}
			set
			{
				if ((this._MADH != value))
				{
					if (this._DONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADHChanging(value);
					this.SendPropertyChanging();
					this._MADH = value;
					this.SendPropertyChanged("MADH");
					this.OnMADHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTHUC", DbType="NVarChar(20)")]
		public string HINHTHUC
		{
			get
			{
				return this._HINHTHUC;
			}
			set
			{
				if ((this._HINHTHUC != value))
				{
					this.OnHINHTHUCChanging(value);
					this.SendPropertyChanging();
					this._HINHTHUC = value;
					this.SendPropertyChanged("HINHTHUC");
					this.OnHINHTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(100)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYMUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYMUA
		{
			get
			{
				return this._NGAYMUA;
			}
			set
			{
				if ((this._NGAYMUA != value))
				{
					this.OnNGAYMUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYMUA = value;
					this.SendPropertyChanged("NGAYMUA");
					this.OnNGAYMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(20)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_USER_GIAODICH", Storage="__USER", ThisKey="MAUSER", OtherKey="MAUSER", IsForeignKey=true)]
		public _USER _USER
		{
			get
			{
				return this.@__USER.Entity;
			}
			set
			{
				_USER previousValue = this.@__USER.Entity;
				if (((previousValue != value) 
							|| (this.@__USER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__USER.Entity = null;
						previousValue.GIAODICHes.Remove(this);
					}
					this.@__USER.Entity = value;
					if ((value != null))
					{
						value.GIAODICHes.Add(this);
						this._MAUSER = value.MAUSER;
					}
					else
					{
						this._MAUSER = default(string);
					}
					this.SendPropertyChanged("_USER");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANG_GIAODICH", Storage="_DONHANG", ThisKey="MADH", OtherKey="MADH", IsForeignKey=true)]
		public DONHANG DONHANG
		{
			get
			{
				return this._DONHANG.Entity;
			}
			set
			{
				DONHANG previousValue = this._DONHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANG.Entity = null;
						previousValue.GIAODICHes.Remove(this);
					}
					this._DONHANG.Entity = value;
					if ((value != null))
					{
						value.GIAODICHes.Add(this);
						this._MADH = value.MADH;
					}
					else
					{
						this._MADH = default(string);
					}
					this.SendPropertyChanged("DONHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIOHANG")]
	public partial class GIOHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAGH;
		
		private System.Nullable<decimal> _THANHTIEN;
		
		private EntitySet<_USER> @__USERs;
		
		private EntitySet<CHITIETGIOHANG> _CHITIETGIOHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGHChanging(string value);
    partial void OnMAGHChanged();
    partial void OnTHANHTIENChanging(System.Nullable<decimal> value);
    partial void OnTHANHTIENChanged();
    #endregion
		
		public GIOHANG()
		{
			this.@__USERs = new EntitySet<_USER>(new Action<_USER>(this.attach__USERs), new Action<_USER>(this.detach__USERs));
			this._CHITIETGIOHANGs = new EntitySet<CHITIETGIOHANG>(new Action<CHITIETGIOHANG>(this.attach_CHITIETGIOHANGs), new Action<CHITIETGIOHANG>(this.detach_CHITIETGIOHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAGH
		{
			get
			{
				return this._MAGH;
			}
			set
			{
				if ((this._MAGH != value))
				{
					this.OnMAGHChanging(value);
					this.SendPropertyChanging();
					this._MAGH = value;
					this.SendPropertyChanged("MAGH");
					this.OnMAGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Money")]
		public System.Nullable<decimal> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOHANG__USER", Storage="__USERs", ThisKey="MAGH", OtherKey="MAGH")]
		public EntitySet<_USER> _USERs
		{
			get
			{
				return this.@__USERs;
			}
			set
			{
				this.@__USERs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOHANG_CHITIETGIOHANG", Storage="_CHITIETGIOHANGs", ThisKey="MAGH", OtherKey="MAGH")]
		public EntitySet<CHITIETGIOHANG> CHITIETGIOHANGs
		{
			get
			{
				return this._CHITIETGIOHANGs;
			}
			set
			{
				this._CHITIETGIOHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__USERs(_USER entity)
		{
			this.SendPropertyChanging();
			entity.GIOHANG = this;
		}
		
		private void detach__USERs(_USER entity)
		{
			this.SendPropertyChanging();
			entity.GIOHANG = null;
		}
		
		private void attach_CHITIETGIOHANGs(CHITIETGIOHANG entity)
		{
			this.SendPropertyChanging();
			entity.GIOHANG = this;
		}
		
		private void detach_CHITIETGIOHANGs(CHITIETGIOHANG entity)
		{
			this.SendPropertyChanging();
			entity.GIOHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITRAICAY")]
	public partial class LOAITRAICAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<TRAICAY> _TRAICAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public LOAITRAICAY()
		{
			this._TRAICAYs = new EntitySet<TRAICAY>(new Action<TRAICAY>(this.attach_TRAICAYs), new Action<TRAICAY>(this.detach_TRAICAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(50)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITRAICAY_TRAICAY", Storage="_TRAICAYs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<TRAICAY> TRAICAYs
		{
			get
			{
				return this._TRAICAYs;
			}
			set
			{
				this._TRAICAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRAICAYs(TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAITRAICAY = this;
		}
		
		private void detach_TRAICAYs(TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAITRAICAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACC_TRAICAY")]
	public partial class NHACC_TRAICAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _MATC;
		
		private System.Nullable<decimal> _GIA;
		
		private System.Nullable<System.DateTime> _NGAYCUNGCAP;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
		private EntityRef<TRAICAY> _TRAICAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnGIAChanging(System.Nullable<decimal> value);
    partial void OnGIAChanged();
    partial void OnNGAYCUNGCAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCUNGCAPChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public NHACC_TRAICAY()
		{
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			this._TRAICAY = default(EntityRef<TRAICAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					if (this._TRAICAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Money")]
		public System.Nullable<decimal> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCUNGCAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCUNGCAP
		{
			get
			{
				return this._NGAYCUNGCAP;
			}
			set
			{
				if ((this._NGAYCUNGCAP != value))
				{
					this.OnNGAYCUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYCUNGCAP = value;
					this.SendPropertyChanged("NGAYCUNGCAP");
					this.OnNGAYCUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NHACC_TRAICAY", Storage="_NHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.NHACC_TRAICAYs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.NHACC_TRAICAYs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_NHACC_TRAICAY", Storage="_TRAICAY", ThisKey="MATC", OtherKey="MATC", IsForeignKey=true)]
		public TRAICAY TRAICAY
		{
			get
			{
				return this._TRAICAY.Entity;
			}
			set
			{
				TRAICAY previousValue = this._TRAICAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAICAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAICAY.Entity = null;
						previousValue.NHACC_TRAICAYs.Remove(this);
					}
					this._TRAICAY.Entity = value;
					if ((value != null))
					{
						value.NHACC_TRAICAYs.Add(this);
						this._MATC = value.MATC;
					}
					else
					{
						this._MATC = default(string);
					}
					this.SendPropertyChanged("TRAICAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private string _EMAIL;
		
		private string _THONGTINNCC;
		
		private EntitySet<NHACC_TRAICAY> _NHACC_TRAICAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTHONGTINNCCChanging(string value);
    partial void OnTHONGTINNCCChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._NHACC_TRAICAYs = new EntitySet<NHACC_TRAICAY>(new Action<NHACC_TRAICAY>(this.attach_NHACC_TRAICAYs), new Action<NHACC_TRAICAY>(this.detach_NHACC_TRAICAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(50)")]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THONGTINNCC", DbType="VarChar(100)")]
		public string THONGTINNCC
		{
			get
			{
				return this._THONGTINNCC;
			}
			set
			{
				if ((this._THONGTINNCC != value))
				{
					this.OnTHONGTINNCCChanging(value);
					this.SendPropertyChanging();
					this._THONGTINNCC = value;
					this.SendPropertyChanged("THONGTINNCC");
					this.OnTHONGTINNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NHACC_TRAICAY", Storage="_NHACC_TRAICAYs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<NHACC_TRAICAY> NHACC_TRAICAYs
		{
			get
			{
				return this._NHACC_TRAICAYs;
			}
			set
			{
				this._NHACC_TRAICAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHACC_TRAICAYs(NHACC_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_NHACC_TRAICAYs(NHACC_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHASANXUAT")]
	public partial class NHASANXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANSX;
		
		private string _TENNSX;
		
		private string _EMAIL;
		
		private string _SDT;
		
		private string _THONGTINNSX;
		
		private string _DIACHI;
		
		private EntitySet<NHASX_TRAICAY> _NHASX_TRAICAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANSXChanging(string value);
    partial void OnMANSXChanged();
    partial void OnTENNSXChanging(string value);
    partial void OnTENNSXChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTHONGTINNSXChanging(string value);
    partial void OnTHONGTINNSXChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    #endregion
		
		public NHASANXUAT()
		{
			this._NHASX_TRAICAYs = new EntitySet<NHASX_TRAICAY>(new Action<NHASX_TRAICAY>(this.attach_NHASX_TRAICAYs), new Action<NHASX_TRAICAY>(this.detach_NHASX_TRAICAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSX", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANSX
		{
			get
			{
				return this._MANSX;
			}
			set
			{
				if ((this._MANSX != value))
				{
					this.OnMANSXChanging(value);
					this.SendPropertyChanging();
					this._MANSX = value;
					this.SendPropertyChanged("MANSX");
					this.OnMANSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNSX", DbType="NVarChar(50)")]
		public string TENNSX
		{
			get
			{
				return this._TENNSX;
			}
			set
			{
				if ((this._TENNSX != value))
				{
					this.OnTENNSXChanging(value);
					this.SendPropertyChanging();
					this._TENNSX = value;
					this.SendPropertyChanged("TENNSX");
					this.OnTENNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THONGTINNSX", DbType="VarChar(100)")]
		public string THONGTINNSX
		{
			get
			{
				return this._THONGTINNSX;
			}
			set
			{
				if ((this._THONGTINNSX != value))
				{
					this.OnTHONGTINNSXChanging(value);
					this.SendPropertyChanging();
					this._THONGTINNSX = value;
					this.SendPropertyChanged("THONGTINNSX");
					this.OnTHONGTINNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHASANXUAT_NHASX_TRAICAY", Storage="_NHASX_TRAICAYs", ThisKey="MANSX", OtherKey="MANSX")]
		public EntitySet<NHASX_TRAICAY> NHASX_TRAICAYs
		{
			get
			{
				return this._NHASX_TRAICAYs;
			}
			set
			{
				this._NHASX_TRAICAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHASX_TRAICAYs(NHASX_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.NHASANXUAT = this;
		}
		
		private void detach_NHASX_TRAICAYs(NHASX_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.NHASANXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHASX_TRAICAY")]
	public partial class NHASX_TRAICAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANSX;
		
		private string _MATC;
		
		private EntityRef<NHASANXUAT> _NHASANXUAT;
		
		private EntityRef<TRAICAY> _TRAICAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANSXChanging(string value);
    partial void OnMANSXChanged();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    #endregion
		
		public NHASX_TRAICAY()
		{
			this._NHASANXUAT = default(EntityRef<NHASANXUAT>);
			this._TRAICAY = default(EntityRef<TRAICAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSX", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANSX
		{
			get
			{
				return this._MANSX;
			}
			set
			{
				if ((this._MANSX != value))
				{
					if (this._NHASANXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANSXChanging(value);
					this.SendPropertyChanging();
					this._MANSX = value;
					this.SendPropertyChanged("MANSX");
					this.OnMANSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					if (this._TRAICAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHASANXUAT_NHASX_TRAICAY", Storage="_NHASANXUAT", ThisKey="MANSX", OtherKey="MANSX", IsForeignKey=true)]
		public NHASANXUAT NHASANXUAT
		{
			get
			{
				return this._NHASANXUAT.Entity;
			}
			set
			{
				NHASANXUAT previousValue = this._NHASANXUAT.Entity;
				if (((previousValue != value) 
							|| (this._NHASANXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHASANXUAT.Entity = null;
						previousValue.NHASX_TRAICAYs.Remove(this);
					}
					this._NHASANXUAT.Entity = value;
					if ((value != null))
					{
						value.NHASX_TRAICAYs.Add(this);
						this._MANSX = value.MANSX;
					}
					else
					{
						this._MANSX = default(string);
					}
					this.SendPropertyChanged("NHASANXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_NHASX_TRAICAY", Storage="_TRAICAY", ThisKey="MATC", OtherKey="MATC", IsForeignKey=true)]
		public TRAICAY TRAICAY
		{
			get
			{
				return this._TRAICAY.Entity;
			}
			set
			{
				TRAICAY previousValue = this._TRAICAY.Entity;
				if (((previousValue != value) 
							|| (this._TRAICAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAICAY.Entity = null;
						previousValue.NHASX_TRAICAYs.Remove(this);
					}
					this._TRAICAY.Entity = value;
					if ((value != null))
					{
						value.NHASX_TRAICAYs.Add(this);
						this._MATC = value.MATC;
					}
					else
					{
						this._MATC = default(string);
					}
					this.SendPropertyChanged("TRAICAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRAICAY")]
	public partial class TRAICAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATC;
		
		private string _MALOAI;
		
		private string _TENTC;
		
		private string _DONVI;
		
		private System.Nullable<decimal> _GIAMOI;
		
		private string _CHITIET;
		
		private System.Nullable<System.DateTime> _HSD;
		
		private System.Nullable<System.DateTime> _NSX;
		
		private System.Nullable<decimal> _GIAMGIA;
		
		private string _LIST_HINHANH;
		
		private System.Nullable<int> _LUOTXEM;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private string _DUONGDAN;
		
		private EntitySet<CHITIETDONHANG> _CHITIETDONHANGs;
		
		private EntitySet<CHITIETGIOHANG> _CHITIETGIOHANGs;
		
		private EntitySet<NHACC_TRAICAY> _NHACC_TRAICAYs;
		
		private EntitySet<NHASX_TRAICAY> _NHASX_TRAICAYs;
		
		private EntityRef<LOAITRAICAY> _LOAITRAICAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENTCChanging(string value);
    partial void OnTENTCChanged();
    partial void OnDONVIChanging(string value);
    partial void OnDONVIChanged();
    partial void OnGIAMOIChanging(System.Nullable<decimal> value);
    partial void OnGIAMOIChanged();
    partial void OnCHITIETChanging(string value);
    partial void OnCHITIETChanged();
    partial void OnHSDChanging(System.Nullable<System.DateTime> value);
    partial void OnHSDChanged();
    partial void OnNSXChanging(System.Nullable<System.DateTime> value);
    partial void OnNSXChanged();
    partial void OnGIAMGIAChanging(System.Nullable<decimal> value);
    partial void OnGIAMGIAChanged();
    partial void OnLIST_HINHANHChanging(string value);
    partial void OnLIST_HINHANHChanged();
    partial void OnLUOTXEMChanging(System.Nullable<int> value);
    partial void OnLUOTXEMChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnDUONGDANChanging(string value);
    partial void OnDUONGDANChanged();
    #endregion
		
		public TRAICAY()
		{
			this._CHITIETDONHANGs = new EntitySet<CHITIETDONHANG>(new Action<CHITIETDONHANG>(this.attach_CHITIETDONHANGs), new Action<CHITIETDONHANG>(this.detach_CHITIETDONHANGs));
			this._CHITIETGIOHANGs = new EntitySet<CHITIETGIOHANG>(new Action<CHITIETGIOHANG>(this.attach_CHITIETGIOHANGs), new Action<CHITIETGIOHANG>(this.detach_CHITIETGIOHANGs));
			this._NHACC_TRAICAYs = new EntitySet<NHACC_TRAICAY>(new Action<NHACC_TRAICAY>(this.attach_NHACC_TRAICAYs), new Action<NHACC_TRAICAY>(this.detach_NHACC_TRAICAYs));
			this._NHASX_TRAICAYs = new EntitySet<NHASX_TRAICAY>(new Action<NHASX_TRAICAY>(this.attach_NHASX_TRAICAYs), new Action<NHASX_TRAICAY>(this.detach_NHASX_TRAICAYs));
			this._LOAITRAICAY = default(EntityRef<LOAITRAICAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._LOAITRAICAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTC", DbType="NVarChar(50)")]
		public string TENTC
		{
			get
			{
				return this._TENTC;
			}
			set
			{
				if ((this._TENTC != value))
				{
					this.OnTENTCChanging(value);
					this.SendPropertyChanging();
					this._TENTC = value;
					this.SendPropertyChanged("TENTC");
					this.OnTENTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONVI", DbType="NVarChar(20)")]
		public string DONVI
		{
			get
			{
				return this._DONVI;
			}
			set
			{
				if ((this._DONVI != value))
				{
					this.OnDONVIChanging(value);
					this.SendPropertyChanging();
					this._DONVI = value;
					this.SendPropertyChanged("DONVI");
					this.OnDONVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMOI", DbType="Money")]
		public System.Nullable<decimal> GIAMOI
		{
			get
			{
				return this._GIAMOI;
			}
			set
			{
				if ((this._GIAMOI != value))
				{
					this.OnGIAMOIChanging(value);
					this.SendPropertyChanging();
					this._GIAMOI = value;
					this.SendPropertyChanged("GIAMOI");
					this.OnGIAMOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET", DbType="NVarChar(MAX)")]
		public string CHITIET
		{
			get
			{
				return this._CHITIET;
			}
			set
			{
				if ((this._CHITIET != value))
				{
					this.OnCHITIETChanging(value);
					this.SendPropertyChanging();
					this._CHITIET = value;
					this.SendPropertyChanged("CHITIET");
					this.OnCHITIETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSD", DbType="DateTime")]
		public System.Nullable<System.DateTime> HSD
		{
			get
			{
				return this._HSD;
			}
			set
			{
				if ((this._HSD != value))
				{
					this.OnHSDChanging(value);
					this.SendPropertyChanging();
					this._HSD = value;
					this.SendPropertyChanged("HSD");
					this.OnHSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSX", DbType="DateTime")]
		public System.Nullable<System.DateTime> NSX
		{
			get
			{
				return this._NSX;
			}
			set
			{
				if ((this._NSX != value))
				{
					this.OnNSXChanging(value);
					this.SendPropertyChanging();
					this._NSX = value;
					this.SendPropertyChanged("NSX");
					this.OnNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMGIA", DbType="Money")]
		public System.Nullable<decimal> GIAMGIA
		{
			get
			{
				return this._GIAMGIA;
			}
			set
			{
				if ((this._GIAMGIA != value))
				{
					this.OnGIAMGIAChanging(value);
					this.SendPropertyChanging();
					this._GIAMGIA = value;
					this.SendPropertyChanged("GIAMGIA");
					this.OnGIAMGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIST_HINHANH", DbType="VarChar(100)")]
		public string LIST_HINHANH
		{
			get
			{
				return this._LIST_HINHANH;
			}
			set
			{
				if ((this._LIST_HINHANH != value))
				{
					this.OnLIST_HINHANHChanging(value);
					this.SendPropertyChanging();
					this._LIST_HINHANH = value;
					this.SendPropertyChanged("LIST_HINHANH");
					this.OnLIST_HINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUOTXEM", DbType="Int")]
		public System.Nullable<int> LUOTXEM
		{
			get
			{
				return this._LUOTXEM;
			}
			set
			{
				if ((this._LUOTXEM != value))
				{
					this.OnLUOTXEMChanging(value);
					this.SendPropertyChanging();
					this._LUOTXEM = value;
					this.SendPropertyChanged("LUOTXEM");
					this.OnLUOTXEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUONGDAN", DbType="NVarChar(50)")]
		public string DUONGDAN
		{
			get
			{
				return this._DUONGDAN;
			}
			set
			{
				if ((this._DUONGDAN != value))
				{
					this.OnDUONGDANChanging(value);
					this.SendPropertyChanging();
					this._DUONGDAN = value;
					this.SendPropertyChanged("DUONGDAN");
					this.OnDUONGDANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_CHITIETDONHANG", Storage="_CHITIETDONHANGs", ThisKey="MATC", OtherKey="MATC")]
		public EntitySet<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this._CHITIETDONHANGs;
			}
			set
			{
				this._CHITIETDONHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_CHITIETGIOHANG", Storage="_CHITIETGIOHANGs", ThisKey="MATC", OtherKey="MATC")]
		public EntitySet<CHITIETGIOHANG> CHITIETGIOHANGs
		{
			get
			{
				return this._CHITIETGIOHANGs;
			}
			set
			{
				this._CHITIETGIOHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_NHACC_TRAICAY", Storage="_NHACC_TRAICAYs", ThisKey="MATC", OtherKey="MATC")]
		public EntitySet<NHACC_TRAICAY> NHACC_TRAICAYs
		{
			get
			{
				return this._NHACC_TRAICAYs;
			}
			set
			{
				this._NHACC_TRAICAYs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAICAY_NHASX_TRAICAY", Storage="_NHASX_TRAICAYs", ThisKey="MATC", OtherKey="MATC")]
		public EntitySet<NHASX_TRAICAY> NHASX_TRAICAYs
		{
			get
			{
				return this._NHASX_TRAICAYs;
			}
			set
			{
				this._NHASX_TRAICAYs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITRAICAY_TRAICAY", Storage="_LOAITRAICAY", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAITRAICAY LOAITRAICAY
		{
			get
			{
				return this._LOAITRAICAY.Entity;
			}
			set
			{
				LOAITRAICAY previousValue = this._LOAITRAICAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAITRAICAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITRAICAY.Entity = null;
						previousValue.TRAICAYs.Remove(this);
					}
					this._LOAITRAICAY.Entity = value;
					if ((value != null))
					{
						value.TRAICAYs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("LOAITRAICAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = this;
		}
		
		private void detach_CHITIETDONHANGs(CHITIETDONHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = null;
		}
		
		private void attach_CHITIETGIOHANGs(CHITIETGIOHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = this;
		}
		
		private void detach_CHITIETGIOHANGs(CHITIETGIOHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = null;
		}
		
		private void attach_NHACC_TRAICAYs(NHACC_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = this;
		}
		
		private void detach_NHACC_TRAICAYs(NHACC_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = null;
		}
		
		private void attach_NHASX_TRAICAYs(NHASX_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = this;
		}
		
		private void detach_NHASX_TRAICAYs(NHASX_TRAICAY entity)
		{
			this.SendPropertyChanging();
			entity.TRAICAY = null;
		}
	}
}
#pragma warning restore 1591
